#https://gitlab.com/lsit-ken3239/live-demo
spring:
  security:
    oauth2:
      client:
        registration:
          gitlab:
            client-id: 8513d917fdee5a6eaf60ee6e0809c4eff51372f8b74c83dfceb557c59f99b4b1
            client-secret: gloas-108dce0fc635106f242ece7447a1730e51f77d45b0c1349cac89643113b140b9
            scope: openid+profile+email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/gitlab
        provider:
          gitlab:
            issuer-uri: https://gitlab.com
            user-name-attribute: sub

